name: Deploy LP1 to Replicate

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: 3.10

      - name: Install Cog
        run: |
          pip install cog

      - name: Login to Replicate and Push
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          cog login --token $REPLICATE_API_TOKEN
          cog push r8.im/turboj3n/lp1v2.3
