name: Deploy LP1 to Replicate

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python manually
        run: |
          sudo apt update
          sudo apt install -y python3.10 python3-pip
          python3.10 -m pip install --upgrade pip

      - name: Install Cog
        run: |
          python3.10 -m pip install cog

      - name: Login to Replicate and Push
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          python3.10 -m cog login --token $REPLICATE_API_TOKEN
          python3.10 -m cog push r8.im/turboj3n/lp1v2.3
